version: '3'

services:
  flask_app:
    image: python:3.9-slim
    container_name: flask_app
    command: python app.py
    volumes:
      - ./flask_app:/app
    ports:
      - "5000:5000"
    networks:
      - my_network

  odoo:
    image: odoo:17
    container_name: odoo
    ports:
      - "8069:8069"
    networks:
      - my_network

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
